trigger:
- main

resources:
  containers:
    - container: postgres
      image: postgres
      networks: 
      - integrationtests
      env:
        POSTGRES_PASSWORD: Postgres2022!
      ports:
        - 5432:5432

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ID CONNECTION'
  imageRepository: 'apisuportepostgres'
  containerRegistry: 'resource.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secretname'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Variáveis para execução dos testes de integração
  File_Log_Execution_WebApp: 'log-execution-restapi.log'
  Path_Project: './APISuporte'
  Dll_Project: 'APISuporte.dll'
  Path_Tests: './Tests'
  Collection_Postman: 'ChamadosSuporte.postman_collection.json'
  Iterations: 10
  BaseSuporteConnectionString: 'Server=127.0.0.1;Port=5432;Database=basesuporte;User Id=postgres;Password=Postgres2022!'
  appsettings_Path: './APISuporte/appsettings.json'

stages:
- stage: Tests
  displayName: Tests stage
  jobs:
  - job: Tests
    displayName: Tests
    pool:
      vmImage: $(vmImageName)
    services:
      postgres: postgres
    steps:
    - script: |
        docker images
        docker container ls
      displayName: Exibir imagens e container em execução
    - script: |
        sleep 10s
        psql postgresql://postgres:Postgres2022!@localhost:5432/postgres -c 'CREATE DATABASE basesuporte;'
        echo 'basesuporte criada com sucesso!'
      displayName: Criar banco basesuporte
    - task: replacetokens@5
      inputs:
        targetFiles: '$(appsettings_Path)'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        defaultValue: '$(BaseSuporteConnectionString)'
        enableTelemetry: true
      displayName: Configurar a string de conexão do PostgreSQL no appsettings.json
    - script: cat $(appsettings_Path)
      displayName: Exibir conteúdo do appsettings.json
    - script: |
        echo '*** SDKs do .NET intalados ***'
        dotnet --list-sdks
        echo '*** Versão assumida como default para o .NET ***'
        dotnet --version
        echo '*** Instalar EF Core Tools ***'
        dotnet tool install --global dotnet-ef
        dotnet ef
      displayName: Instalar EF Core Tools
    - script: |
        cd $(Path_Project)
        dotnet ef migrations add IntegrationTests
        dotnet ef database update
        echo 'Migrations do Entity Framework Core executadas com sucesso'
      displayName: Executar Migrations criando a tabela de Chamados
    - script: |
        dotnet publish $(Path_Project) -c Release -o app
        cd ./app
        nohup dotnet $(Dll_Project) > $(File_Log_Execution_WebApp) 2>&1 &
        echo 'Aguardando a inicialização da aplicação a ser testada...'
        sleep 10s
      displayName: Executar a aplicação a ser testada em background (nohup)
      env:
        ASPNETCORE_URLS: 'http://localhost:5000'
    - script: |
        cd $(Path_Tests)
        newman run $(Collection_Postman) -n $(Iterations)
      displayName: Executar testes da API REST com Newman
      condition: always() 
    - script: psql postgresql://postgres:Postgres2022!@localhost:5432/basesuporte -c 'SELECT * FROM "Chamados";'
      condition: always() 
      displayName: Exibir registros criados na base de dados
    - script: |
        echo "** Versão Global do Newman **"
        newman -v
        npm install newman-reporter-htmlextra@1.22.11
        npm install newman-reporter-junitfullreport@1.0.4
      displayName:  Instalar packages newman-reporter-htmlextra e newman-reporter-junitfullreport
      condition: always() 
    - script: |
        cd $(Path_Tests)
        npx newman run $(Collection_Postman) -n $(Iterations) -r htmlextra,junitfullreport
        cd ./newman
        ls
      displayName: Gerar resultados em HTML e XML dos testes da API REST com Newman
      condition: always()
    - script: psql postgresql://postgres:Postgres2022!@localhost:5432/basesuporte -c 'SELECT * FROM "Chamados";'
      condition: always() 
      displayName: Exibir registros criados na base de dados após segundo conjunto de testes
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/newman/*.xml'
        searchFolder: '$(Build.SourcesDirectory)'
      displayName: Publicar sumário dos testes com base no XML gerado
      condition: always()
    - task: UploadPostmanHtmlReport@1
      displayName: Publicar relatório em HTML com resultados dos testes da API REST com Newman
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)/$(Path_Tests)'
      condition: always()
    - script: |
        cd ./app
        cat $(File_Log_Execution_WebApp)
      displayName: Exibir log de execução da aplicação testada
      condition: Always()

- stage: Build
  displayName: Build stage
  dependsOn: Tests
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'Suporte.chamadospostgres'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

